// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYY9UXks6zSVAYXXgLbt4C36u2v_meJek',
    appId: '1:819606405773:android:1c7ae92c5993caa12358c4',
    messagingSenderId: '819606405773',
    projectId: 'face-recognition-8ac2f',
    databaseURL: 'https://face-recognition-8ac2f-default-rtdb.firebaseio.com',
    storageBucket: 'face-recognition-8ac2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtTSNnj5FV04vPAGFJmBVb2ZxOt8qAg4Q',
    appId: '1:819606405773:ios:085cc4cf0e3d87572358c4',
    messagingSenderId: '819606405773',
    projectId: 'face-recognition-8ac2f',
    databaseURL: 'https://face-recognition-8ac2f-default-rtdb.firebaseio.com',
    storageBucket: 'face-recognition-8ac2f.appspot.com',
    iosBundleId: 'com.amaryllis.presensi',
  );
}
